name: "TESTMODEL"
jk_type: "cat"  # "cat" or "lstm" or "max" or "attention"
encoder_type: "Encoder4" # "Encoder1" or "Encoder2" or "Encoder3"

# Encoder1: GIN + GCN + JK-Net
# Encoder2: GCN + JK-Net aggregations
# Encoder3: GCN + JK-Net + residual connections

# Encoder4: GIN + GCN + JK-Net(cat) + residual connections
# Encoder5: GIN + JK-Net(cat) + residual connections