defaults:
  - dataset: CIC-IDS-2017
  - model: BTIG_GNN
  - _self_

task:
  binary: True

hyperparameters:
  learning_rate: 0.005
  weight_decay: 0.5
  batch_size: 32
  epochs: 64
  dropout_rate: 0.1
  hidden_size: 64
  optimizer: "adam"
  device: "cuda"  # or "cpu" if CUDA is not available
  patience: 10
  num_node_features: 3
  num_statistical_features: 12

parameters:
  max_nodes: 25
  burst_threshold: 5

output_settings:
  checkpoint_dir: "checkpoints/"
  best_model_path: "${hydra:run.dir}/best_model.pth"
