defaults:
  - dataset: CIC-IDS-2017
  - model: TIG_CONTRASTIVE
  - _self_

graph: "TIG" # "TIG" or "FG"
mode: "both" # "pretrain" or "finetune" or "both"
pretrained_model_path: ""

obfuscation: 
  stage: "stage3" #   "stage1" or "stage2" or "stage1_2"
  probability: 0.2  # 概率为0.5表示每个batch中有50%的概率进行obfuscation
  rate: 0.8

task:
  binary: False

hyperparameters:
  learning_rate: 0.005
  weight_decay: 0.1
  batch_size: 8192
  epochs: 500
  dropout_rate: 0.1
  hidden_size: 128
  optimizer: "adam"
  device: "cuda"  # or "cpu" if CUDA is not available
  patience: 10
  num_node_features: 3
  num_statistical_features: 12

  finetune_lr: 0.0001  # 微调学习率，通常比预训练小
  finetune_epochs: 50  # 微调轮数
  freeze_encoder: True  # 是否冻结编码器参数
  dropout: 0.3  # 分类器的dropout率
  n_shot: 20

parameters:
  max_nodes: 25
  burst_threshold: 5

output_settings:
  checkpoint_dir: "checkpoints/"
  initial_model_path: "${hydra:run.dir}/best_pretrain_model.pth"
  best_model_path: "${hydra:run.dir}/best_pretrain_model.pth"
  best_finetune_model: "${hydra:run.dir}/best_finetune_model.pth"

